AllCops:
  TargetRubyVersion: 2.5

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/LineLength:
  Exclude:
    - profiles/**/*.rb
    - gatherlogs.gemspec
    - spec/**/*.rb
    - gatherlogs_reporter.gemspec

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Max: 20

Metrics/AbcSize:
  Max: 30

Metrics/BlockLength:
  Max: 35
  Exclude:
    - spec/**/*.rb
    - gatherlogs_reporter.gemspec

Layout/FirstHashElementIndentation:
  Enabled: false

Naming/HeredocDelimiterNaming:
  Enabled: false

Style/FormatStringToken:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

Metrics/ClassLength:
  Max: 200

# These are ugly
Style/ConditionalAssignment:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Style/Alias:
  Enabled: false

Style/StringLiterals:
  Enabled: false
