AllCops:
  TargetRubyVersion: 2.5

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/LineLength:
  Exclude:
    - profiles/**/*.rb
    - gatherlogs.gemspec
    - spec/**/*.rb

Metrics/BlockLength:
  Exclude:
    - spec/**/*.rb

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Max: 20 

Metrics/AbcSize:
  Max: 30

Metrics/BlockLength:
  Max: 35
  Exclude: 
    - spec/**/*.rb

Layout/IndentHash:
  Enabled: false

Naming/HeredocDelimiterNaming:
  Enabled: false

Style/FormatStringToken:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

Metrics/ClassLength:
  Max: 200
